# _config.yml is a basic golbal setting of the whole site

theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"


# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://yxy92.github.io/
baseurl: /yxy92
title: Xiangyu Yao
author: Xiangyu Yao
description: Personal blog and resume
avatar: image/twitter_avatar.jpg
email: jacky92@vt.edu



# needed for travis-ci build
exclude: [vendor]
