# _config.yml is a basic golbal setting of the whole site




# edit here to achieve your personal greatness
url: http://yxy92.github.io/
baseurl: /yxy92
title: Xiangyu Yao's personal homepage
author: Xiangyu Yao
description: This is the my personal homepage sharing my thoughts and experience. 
avatar: image/twitter_avatar.jpg
email: jacky92@vt.edu



# needed for travis-ci build
exclude: [vendor]
