import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");
const sources=[
  {publication:"Quanta Magazine",field:"Science",feed:"https://api.quantamagazine.org/feed/",weight:10},
  {publication:"Aeon",field:"Philosophy & Culture",feed:"https://aeon.co/feed.rss",weight:9},
  {publication:"Noema",field:"Civilization & Technology",feed:"https://www.noemamag.com/feed/",weight:9},
  {publication:"Works in Progress",field:"Economics & Society",feed:"https://worksinprogress.co/feed/",weight:9},
  {publication:"Nautilus",field:"Science & Mind",feed:"https://nautil.us/feed/",weight:8},
  {publication:"MIT Press Reader",field:"Ideas & Technology",feed:"https://thereader.mitpress.mit.edu/feed/",weight:8}
];
const reject=/\b(newsletter|podcast|video|quiz|job|event|conference|announcement|weekly|roundup|review of the week)\b/i;
const decode=(s="")=>s.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,"$1").replace(/<[^>]+>/g," ").replace(/&nbsp;/g," ").replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/\s+/g," ").trim();
const tag=(block,names)=>{for(const name of names){const m=block.match(new RegExp(`<${name}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${name}>`,"i"));if(m)return decode(m[1]);}return"";};
const attrLink=block=>block.match(/<link[^>]+href=["']([^"']+)["']/i)?.[1]||"";
const note=s=>{const clean=decode(s).replace(/\s*(The post .*? appeared first on .*?\.)$/i,"").trim();const sentence=clean.match(/^.{70,190}?[.!?](?:\s|$)/)?.[0]?.trim();if(sentence)return sentence;const cut=clean.slice(0,177).replace(/\s+\S*$/,"");return cut?`${cut}…`:"A substantial new essay selected for today’s cross-disciplinary reading list.";};
const classify=(text,fallback)=>{const t=text.toLowerCase();if(/math|proof|number theory|geometry|algebra|percolation/.test(t))return"Mathematics";if(/computer|algorithm|software|machine|artificial intelligence|\bai\b|internet/.test(t))return"Technology";if(/econom|market|growth|trade|food|city|housing|policy/.test(t))return"Economics & Society";if(/history|ancient|archive|century|empire|war /.test(t))return"History";if(/philosoph|ethic|meaning|reality|subjective|religio/.test(t))return"Philosophy";if(/quantum|physics|cosmos|universe|particle|astronom/.test(t))return"Physics";if(/brain|mind|cognit|conscious|psycholog|neuro/.test(t))return"Mind";if(/ecolog|climate|biology|evolution|animal|plant|genetic/.test(t))return"Life & Earth";return fallback;};
async function fetchText(url,timeout=15000){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);try{const res=await fetch(url,{headers:{"user-agent":"FiveDailyBot/1.0 (+https://yxy92.github.io/five-daily/)"},signal:controller.signal,redirect:"follow"});if(!res.ok)throw new Error(`${res.status}`);return await res.text();}finally{clearTimeout(timer);}}
function parseFeed(xml,source){const blocks=[...(xml.match(/<item\b[\s\S]*?<\/item>/gi)||[]),...(xml.match(/<entry\b[\s\S]*?<\/entry>/gi)||[])];return blocks.map(block=>({...source,title:tag(block,["title"]),url:tag(block,["link"])||attrLink(block),author:tag(block,["dc:creator","author","name"])||source.publication,published:tag(block,["pubDate","published","updated","dc:date"]),description:tag(block,["content:encoded","description","summary","content"])})).filter(x=>x.title&&/^https?:/.test(x.url)&&!reject.test(x.title));}
async function inspect(c){try{const html=await fetchText(c.url,12000),main=html.match(/<article\b[\s\S]*?<\/article>/i)?.[0]||html,text=decode(main.replace(/<script\b[\s\S]*?<\/script>/gi,"").replace(/<style\b[\s\S]*?<\/style>/gi,"")),words=text.split(/\s+/).filter(Boolean).length,minutes=Math.max(1,Math.round(words/230));return{...c,field:classify(`${c.title} ${c.description}`,c.field),minutes,words,note:note(c.description||text.slice(0,700))};}catch{return null;}}
const current=JSON.parse(await fs.readFile(path.join(root,"data/reads.json"),"utf8")),history=JSON.parse(await fs.readFile(path.join(root,"data/history.json"),"utf8")),cutoff=Date.now()-90*864e5,recentHistory=history.filter(x=>new Date(x.featuredAt).getTime()>cutoff),seen=new Set(recentHistory.map(x=>x.url));
const results=await Promise.allSettled(sources.map(async s=>parseFeed(await fetchText(s.feed),s)));let candidates=results.flatMap(r=>r.status==="fulfilled"?r.value:[]).filter(x=>!seen.has(x.url));candidates=candidates.filter(x=>!x.published||Date.now()-new Date(x.published).getTime()<45*864e5);
const inspected=(await Promise.all(candidates.slice(0,45).map(inspect))).filter(Boolean).filter(x=>x.minutes>=10&&x.minutes<=30);inspected.sort((a,b)=>(b.weight+(Date.parse(b.published)||0)/1e13)-(a.weight+(Date.parse(a.published)||0)/1e13));
const chosen=[],fields=new Set(),publications=new Map();for(const item of inspected){if(fields.has(item.field)||((publications.get(item.publication)||0)>=1&&chosen.length<4))continue;chosen.push(item);fields.add(item.field);publications.set(item.publication,(publications.get(item.publication)||0)+1);if(chosen.length===5)break;}for(const item of inspected){if(chosen.length===5)break;if(!chosen.some(x=>x.url===item.url))chosen.push(item);}if(chosen.length<5)for(const item of current.reads){if(chosen.length===5)break;if(!chosen.some(x=>x.url===item.url))chosen.push(item);}
const now=new Date(),date=now.toISOString().slice(0,10),payload={date,edition:Math.floor((Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate())-Date.UTC(2026,0,1))/864e5)+1,reads:chosen.slice(0,5).map(x=>({field:x.field,minutes:x.minutes,title:x.title,author:x.author,publication:x.publication,url:x.url,note:x.note}))};
await fs.writeFile(path.join(root,"data/reads.json"),JSON.stringify(payload,null,2)+"\n");const merged=[...recentHistory,...payload.reads.map(x=>({url:x.url,featuredAt:date}))].filter((x,i,a)=>a.findIndex(y=>y.url===x.url)===i);await fs.writeFile(path.join(root,"data/history.json"),JSON.stringify(merged,null,2)+"\n");console.log(`Selected ${payload.reads.length} reads from ${inspected.length} eligible essays.`);
